[workspace]
resolver = "2"
members = [ "demo","wasm-serialize", "wasm-serialize-derive"]

[workspace.dependencies]
wasm-serialize = { path = "wasm-serialize" }
wasm-serialize-derive = { path = "wasm-serialize-derive" }
wasm-bindgen = "0.2.83"
js-sys = "0.3.69"

[profile.release]
lto = true
